# Change these first
owner: Mk1Yoyos # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Mk1 Yoyos
    url: https://mk1yoyos.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mk1 Yoyos Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Is Mk1 Yoyos up or down? [**Get your own yoyo here**](https://mk1yoyos.com/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
